name: explode
description: >-
  A lightweight Flutter package that turns any widget into a satisfying
  particle explosion with customizable shapes, speed, density, and spread area.
version: 1.0.0
homepage: https://github.com/Krutikgohel/explode
repository: https://github.com/Krutikgohel/explode
issue_tracker: https://github.com/Krutikgohel/explode/issues
documentation: https://github.com/Krutikgohel/explode#readme

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
